CREATE TABLE WORKOUT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT
    );

CREATE TABLE EXERCISE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    PRIMARY_TARGET_MUSCLE TEXT,
    SECONDARY_TARGET_MUSCLE TEXT,
    SETS INTEGER,
    REPS INTEGER,
    FOREIGN KEY(WORKOUT_ID) REFERENCES WORKOUT(ID)
    );

CREATE TABLE USER(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRSTNAME TEXT,
    LASTNAME TEXT,
    EMAIL TEXT,
    PASSWORD TEXT,
    GOOGLEACCOUNT INTEGER
    );

CREATE TABLE PROGRESS_HISTORY(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISE(ID),
    INITIAL_WEIGHT REAL,
    CURRENT_WEIGHT REAL
    );

CREATE TABLE REPORT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMENT TEXT
    );
