CREATE TABLE IF NOT EXISTS WORKOUT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT
    );

CREATE TABLE IF NOT EXISTS EXERCISE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    PRIMARY_TARGET_MUSCLE TEXT,
    SECONDARY_TARGET_MUSCLE TEXT,
    SETS INTEGER,
    REP1 INTEGER, REP2 INTEGER, REP3 INTEGER,
    REP4 INTEGER, REP5 INTEGER, REP6 INTEGER,
    WORKOUT_ID INTEGER,
    FOREIGN KEY(WORKOUT_ID) REFERENCES WORKOUT(ID)
    );

CREATE TABLE IF NOT EXISTS USER(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRSTNAME TEXT,
    LASTNAME TEXT,
    USERNAME TEXT,
    EMAIL TEXT,
    PASSWORD TEXT,
    GOOGLEACCOUNT INTEGER
    );

CREATE TABLE IF NOT EXISTS PROGRESS_HISTORY(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EXERCISE_ID INTEGER,
    INITIAL_WEIGHT REAL,
    CURRENT_WEIGHT REAL,
    FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISE(ID)
    );

CREATE TABLE IF NOT EXISTS REPORT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMMENT TEXT
    );
