CREATE TABLE temp (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    PRIMARY_TARGET_MUSCLE TEXT,
    SECONDARY_TARGET_MUSCLE TEXT,
    SETS INTEGER,
    REP1 INTEGER, REP2 INTEGER, REP3 INTEGER,
    REP4 INTEGER, REP5 INTEGER, REP6 INTEGER,
    FOREIGN KEY(WORKOUT_ID) REFERENCES WORKOUT(ID)
    );

DROP TABLE EXERCISE;

ALTER TABLE temp RENAME TO EXERCISE;